{
 "title": "Highload HW3",
 "time": { "from": "2020-10-13T18:06:36.866Z", "to": "2020-10-13T18:13:12.913Z" },
 "panels": [
  {
   "title": "CPU Summary (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"Orletskiy-1-server\"}[15s])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"Orletskiy-2-server\"}[15s])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"Orletskiy-3-server\"}[15s])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"Orletskiy-balancer-server\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPS Summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hits_counter{job=\"Orletskiy-1-backend\"}[15s])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "irate(hits_counter{job=\"Orletskiy-2-backend\"}[15s])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "irate(hits_counter{job=\"Orletskiy-3-backend\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Balancer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"Orletskiy-balancer-server\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "CPU Orletskiy-1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"Orletskiy-1-server\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPS Orletskiy-1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hits_counter{job=\"Orletskiy-1-backend\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Orletskiy-2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"Orletskiy-2-server\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPS Orletskiy-2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hits_counter{job=\"Orletskiy-2-backend\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Orletskiy-3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"Orletskiy-3-server\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPS Orletskiy-3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hits_counter{job=\"Orletskiy-3-backend\"}[15s])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}